version: '3'

services:
  wp:
    image: ${WP_VERSION} # https://hub.docker.com/_/wordpress/
    ports:
      - 127.0.0.1:80:80 # change ip if required
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html/wp-includes # Full wordpress project
      - ./wp-app/wp-config.php:/var/www/html/wp-config.php # Full wordpress project
      - ./starter-theme/:/var/www/html/wp-content/themes/starter-theme # Theme development
      - ./src/themes/:/var/www/html/wp-content/themes
      - ./src/plugins/:/var/www/html/wp-content/plugins
      - ./src/uploads/:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks: 
    - web-networks 

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PMADB=${MYSQL_DATABASE}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_CONTROLUSER=${DB_USER}
      - PMA_CONTROLPASS=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=1G
    ports:
      - 9000:80
    networks: 
      - web-networks 
volumes:
  db_data:
